class BagItems {
  int id;
  String name;
  String price;
  String rating;
  String image;
  String description;
  BagItems(this.id, this.name, this.price, this.rating, this.image,
      this.description);
}

List<BagItems> bagList = [
  BagItems(1, "Green blog", "4799", "4.1", "assets/images/bag_2.png",
      "Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort!"),
  BagItems(2, "Orange fang", "5000", "3.8", "assets/images/bag_3.png",
      "Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort!"),
  BagItems(3, "Dark grass", "3599", "4.0", "assets/images/bag_4.png",
      "Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort!"),
  BagItems(4, "Neon fight", "6199", "4.6", "assets/images/bag5.png",
      "Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort!"),
];
List<BagItems> bagList2 = [
  BagItems(1, "Neon fight", "6199", "4.6", "assets/images/bag5.png",
      "Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort!"),
  BagItems(2, "Green blog", "4799", "4.1", "assets/images/bag_2.png",
      "Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort!"),
  BagItems(3, "Orange fang", "5000", "3.8", "assets/images/bag_3.png",
      "Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort!"),
  BagItems(4, "Dark grass", "3599", "4.0", "assets/images/bag_4.png",
      "Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort! Travel gets a new meaning when you have a travel squad set to compliment all your wanderlust goals. The different sizes make it easy to choose from depending on the occasion and the polycarbonate shell keeps it light, scratch-free and long-lasting. Walk-in with confidence and check-in with comfort!"),
];
